# LG GT540
TARGET_GLOBAL_CFLAGS += -mfpu=vfp -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mfpu=vfp -mfloat-abi=softfp

# CAMERA
USE_CAMERA_STUB := false
TARGET_DISABLE_ARM_PIE := true

# BOARD PROPERTIES
TARGET_BOARD_PLATFORM := msm7x27
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
TARGET_ARCH := arm
TARGET_CPU_ABI := armeabi-v6l
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv6-vfp
ARCH_ARM_HAVE_VFP := true

# BOOTLOADER
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := swift
TARGET_OTA_ASSERT_DEVICE := swift

# PARTITIONS
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x00500000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x00900000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x0f500000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x08a80000
BOARD_FLASH_BLOCK_SIZE := 131072

# AUDIO
TARGET_PROVIDES_LIBAUDIO := true
BOARD_USES_GENERIC_AUDIO := false
BOARD_USES_AUDIO_LEGACY := false
BOARD_COMBO_DEVICE_SUPPORTED := true
BOARD_CDMA_NETWORK := true
BOARD_USES_ICS_LIBAUDIO := true

# BLUETOOTH
BOARD_HAVE_BLUETOOTH := true
BOARD_HAVE_BLUETOOTH_BCM := true
BOARD_CUSTOM_BRCM_PATCHRAM_PLUS := ../../../device/lge/swift/prebuilt/brcm_patchram_plus.c

# FM RADIO
BOARD_FM_DEVICE := bcm4325
BOARD_HAVE_FM_RADIO := true
BOARD_GLOBAL_CFLAGS += -DHAVE_FM_RADIO
BOARD_GLOBAL_CFLAGS += -DFM_RADIO

# GPS
BOARD_USES_QCOM_GPS := true
BOARD_VENDOR_QCOM_GPS_LOC_API_HARDWARE := swift
BOARD_VENDOR_QCOM_GPS_LOC_API_AMSS_VERSION := 1240

# GSM RADIO
BOARD_PROVIDES_LIBRIL := true
BOARD_USE_NEW_LIBRIL_HTC := true

# HEADERS
TARGET_SPECIFIC_HEADER_PATH := device/lge/swift/include

# USB
TARGET_USE_CUSTOM_LUN_FILE_PATH := "/sys/class/android_usb/android0/f_mass_storage/lun/file"

# KERNEL
TARGET_KERNEL_SOURCE := kernel/lge/swift
TARGET_KERNEL_CONFIG := cyanogenmod_swift_defconfig
TARGET_PREBUILT_KERNEL := device/lge/swift/prebuilt/kernel/zImage
BOARD_KERNEL_CMDLINE := mem=214M console=ttyMSM2,115200n8 androidboot.hardware=swift
BOARD_KERNEL_BASE := 0x00200000
BOARD_PAGE_SIZE := 0x00000800

# QUALCOMM
BOARD_USES_QCOM_HARDWARE := true
BOARD_USES_QCOM_LIBS := true
BOARD_USES_QCOM_LIBRPC := true
BOARD_USES_QCOM_LEGACY := true
#BOARD_HAVE_QCOM_FM := true
#BOARD_QCOM_FM_ENABLED := true

# Wifi
BOARD_WLAN_DEVICE               := bcm4325
WIFI_DRIVER_FW_PATH_STA         := "/system/etc/wl/rtecdc.bin"
WIFI_DRIVER_FW_PATH_AP          := "/system/etc/wl/rtecdc-apsta.bin"
WIFI_DRIVER_MODULE_NAME         := "wireless"
WIFI_DRIVER_MODULE_PATH         := "/system/lib/modules/wireless.ko"
WIFI_DRIVER_MODULE_ARG          := "firmware_path=/system/etc/wl/rtecdc.bin nvram_path=/system/etc/wl/nvram.txt"
WPA_SUPPLICANT_VERSION          := VER_0_6_X
HOSTAPD_VERSION 		:= VER_0_6_X
WIFI_SDIO_IF_DRIVER_MODULE_PATH := "/system/lib/modules/librasdioif.ko"
WIFI_SDIO_IF_DRIVER_MODULE_NAME := "librasdioif"
WIFI_SDIO_IF_DRIVER_MODULE_ARG  := ""
BOARD_WPA_SUPPLICANT_DRIVER     := WEXT
WIFI_DRIVER_HAS_LGE_SOFTAP      := true

# Sensors
BOARD_VENDOR_USE_AKMD := akm8973
TARGET_USES_OLD_LIBSENSORS_HAL := true
TARGET_SENSORS_NO_OPEN_CHECK := true

# JB FLAGS
BOARD_NEEDS_MEMORYHEAPPMEM := true
BOARD_USE_NASTY_PTHREAD_CREATE_HACK := true
TARGET_USES_16BPPSURFACE_FOR_OPAQUE := true
TARGET_AVOID_DRAW_TEXTURE_EXTENSION := true
DISABLE_DEXPREOPT := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_USE_SKIA_LCDTEXT := true
BOARD_USE_LEGACY_TOUCHSCREEN := true
WITH_JIT := true
ENABLE_JSC_JIT := true
JS_ENGINE := v8
HTTP := chrome
ENABLE_WEBGL := true
TARGET_FORCE_CPU_UPLOAD := true

# GRAPHICS
BOARD_USES_HWCOMPOSER := false
TARGET_DISABLE_TRIPLE_BUFFERING := true
TARGET_NO_HW_VSYNC := true
BOARD_EGL_CFG := device/lge/swift/proprietary/lib/egl/egl.cfg
USE_OPENGL_RENDERER := true
BOARD_USES_GENLOCK := true
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true
TARGET_GRALLOC_USES_ASHMEM := true
TARGET_USE_OVERLAY := false
TARGET_HAVE_BYPASS := false
TARGET_USES_C2D_COMPOSITION := false
TARGET_QCOM_HDMI_OUT := false
TARGET_BOOTANIMATION_NAME := vertical-320
TARGET_BOOTANIMATION_USE_RGB565 := true
TARGET_BOOTANIMATION_PRELOAD := true
TARGET_BOOTANIMATION_TEXTURE_CACHE := true
TARGET_SCREEN_HEIGHT := 480
TARGET_SCREEN_WIDTH := 320

#Flags
COMMON_GLOBAL_CFLAGS += -DTARGET_MSM7x27
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE
COMMON_GLOBAL_CFLAGS += -DREFRESH_RATE=56
COMMON_GLOBAL_CFLAGS += -DBINDER_COMPAT
COMMON_GLOBAL_CFLAGS += -DDECIDE_TEXTURE_TARGET
COMMON_GLOBAL_CFLAGS += -DQCOM_ICS_COMPAT
COMMON_GLOBAL_CFLAGS += -DQCOM_NO_SECURE_PLAYBACK
COMMON_GLOBAL_CFLAGS += -DICS_AUDIO_BLOB
#COMMON_GLOBAL_CFLAGS += -DUSES_LEGACY_EGL
#BOARD_FRAMEBUFFER_FORCE_FORMAT := RGB565
#TARGET_BUILD_PDK := true
#QCOM_ICS_DECODERS := true
